# This file defines which GitHub labels get applied when files
# matching certain minimatch glob patterns are changed.
#
# Documentation: https://github.com/actions/labeler#pull-request-labeler
#
# If a label includes a space or a pattern begins with an asterisk or
# special character, enclose it in quotes.

'changes existing API':
  - changed-files:
    - any-glob-to-any-file: 'changelog/*.breaking*.rst'

bug:
  - changed-files:
    - any-glob-to-any-file: 'changelog/*.bugfix*.rst'

CI:
  - changed-files:
    - any-glob-to-any-file: [
      'codecov.yaml',
      '.github/workflows/*test*.yml',
      '.pre-commit-config.yaml',
      '.readthedocs.yml',
      'mypy.ini',
      'noxfile.py',
      'tox.ini'
    ]

'contributor guide':
  - changed-files:
    - any-glob-to-any-file: ['changelog/README.rst', 'docs/contributing/**/*']

dependencies:
  - changed-files:
    - any-glob-to-any-file: '**/*requirements*.txt'

docs:
  - changed-files:
    - any-glob-to-any-file: ['.readthedocs.yml', 'changelog/*doc*.rst', 'docs/**/*']

'GitHub Actions':
  - changed-files:
    - any-glob-to-any-file: '.github/**/*'

linters:
  - changed-files:
    - any-glob-to-any-file: ['.sourcery.yaml', '.pre-commit*.yaml']

maintenance:
  - changed-files:
    - any-glob-to-any-file: [
      '**/.editorconfig',
      '.git-blame-ignore-revs',
      '.gitattributes',
      '.gitignore',
      '.mailmap',
      'CODEOWNERS',
      '**/README*'
    ]

notebooks:
  - changed-files:
    - any-glob-to-any-file: [
      'docs/notebooks/**/*',
      '**/*.ipynb',
      '**/binder/**/*',
      '.jupyter/**/*'
    ]

nox:
  - changed-files:
    - any-glob-to-any-file: '**/noxfile.py'

packaging:
  - changed-files:
    - any-glob-to-any-file: [
      '.github/workflows/*publish*',
      '.github/workflows/*pypi*',
      '.github/workflows/*release*',
      'LICENSE.md',
      'MANIFEST.in',
      'PATENT.md',
      'pyproject.toml',
      '**/scm_version.py',
      'setup.*'
    ]

'physical data':
  - changed-files:
    - any-glob-to-any-file: [
      '**/particles/data/**/*',
      '**/tools/export_ionization_energy.py'
    ]

plasmapy.analysis:
  - changed-files:
    - any-glob-to-any-file: '**/analysis/**/*'

plasmapy.diagnostics:
  - changed-files:
    - any-glob-to-any-file: '**/diagnostics/**/*'

plasmapy.dispersion:
  - changed-files:
    - any-glob-to-any-file: '**/dispersion/**/*'

plasmapy.formulary:
  - changed-files:
    - any-glob-to-any-file: '**/formulary/**/*'

plasmapy.formulary.quantum:
  - changed-files:
    - any-glob-to-any-file: '**/quantum*'

plasmapy.particles:
  - changed-files:
    - any-glob-to-any-file: '**/particles/**/*'

plasmapy.plasma:
  - changed-files:
    - any-glob-to-any-file: '**/plasma/**/*'

plasmapy.simulation:
  - changed-files:
    - any-glob-to-any-file: '**/simulation/**/*'

plasmapy.utils:
  - changed-files:
    - any-glob-to-any-file: '**/utils/**/*'

release:
  - changed-files:
    - any-glob-to-any-file: [
      '.github/workflows/*publish*',
      '.github/workflows/*pypi*',
      '.github/workflows/*release*',
    ]

'static type checking':
  - changed-files:
    - any-glob-to-any-file: [
      '**/*mypy*',
      '**/type_stubs/**/*',
      '**/py.typed'
    ]

testing:
  - changed-files:
    - any-glob-to-any-file: [
      '**/tests/**/*',
      '**/test*.py',
      '**/conftest.py',
      '.github/workflows/weekly-tests.yml',
      '.codecov.yaml',
      'noxfile.py',
      'tox.ini'
    ]

tools:
  - changed-files:
    - any-glob-to-any-file: ['tools/**/*']
