Breaking:
- changelog/*.breaking*rst

Contributor Guide:
- docs/contributing/**/*

dependencies:
- requirements.txt

Documentation:
- any: [docs/**/*]
  all: ['!docs/notebooks/**/*', '!docs/contributing/*']

GitHub Actions:
- .github/**/*

Notebooks:
- docs/notebooks/**/*

plasmapy.analysis:
- plasmapy/analysis/**/*

plasmapy.diagnostics:
- plasmapy/diagnostics/**/*

plasmapy.dispersion:
- plasmapy/dispersion/**/*

plasmapy.formulary:
- plasmapy/formulary/**/*

plasmapy.formulary.quantum:
- any: [plasmapy/formulary/quantum.py, plasmapy/formulary/tests/test_quantum.py]

plasmapy.particles:
- plasmapy/particles/**/*

plasmapy.plasma:
- plasmapy/plasma/**/*

plasmapy.simulation:
- plasmapy/simulation/**/*

plasmapy.utils:
- plasmapy/utils/**/*
