Breaking:
- changelog/*.breaking*rst

Continuous Integration:
- any: ['.codecov.yaml', '.pre-commit-config.yaml', 'CODEOWNERS', 'noxfile.py', 'tox.ini']

Contributor Guide:
- any: ['changelog/README.rst', 'docs/contributing/**/*']

dependencies:
- requirements.txt

Documentation:
- any: ['docs/**/*', 'changelog/*doc*.rst', 'README.md', '.readthedocs.yml']
  all: ['!docs/notebooks/**/*', '!docs/contributing/*']

GitHub Actions:
- .github/**/*

Notebooks:
- docs/notebooks/**/*

Packaging:
- any: ['MANIFEST.in', 'pyproject.toml', 'setup.cfg', 'setup.py']

plasmapy.analysis:
- plasmapy/analysis/**/*

plasmapy.diagnostics:
- plasmapy/diagnostics/**/*

plasmapy.dispersion:
- plasmapy/dispersion/**/*

plasmapy.formulary:
- plasmapy/formulary/**/*

plasmapy.formulary.quantum:
- any: ['plasmapy/formulary/quantum.py', 'plasmapy/formulary/tests/test_quantum.py']

plasmapy.particles:
- plasmapy/particles/**/*

plasmapy.plasma:
- plasmapy/plasma/**/*

plasmapy.simulation:
- plasmapy/simulation/**/*

plasmapy.utils:
- plasmapy/utils/**/*
