codecov:
  token: 85c13d8a-e9e1-49fd-97d4-7ba103f3e830
coverage:
  status:
    project:
      default:
        threshold: 0.2%
        if_ci_failed: ignore
        require_ci_to_pass: yes
        wait_for_ci: no
        removed_code_behavior: adjust_base
