codecov:
  token: 85c13d8a-e9e1-49fd-97d4-7ba103f3e830
  notify:
    wait_for_ci: no
  require_ci_to_pass: yes
coverage:
  status:
    project:
      default:
        target: 96%
        threshold: 0.25%
        removed_code_behavior: adjust_base
