# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

formats:
- htmlzip

build:
  os: ubuntu-22.04
  tools:
    # Use most recent version supported by Numba
    python: '3.11'
  apt_packages:
  - graphviz
  jobs:
    post_build:
    - echo https://docs.plasmapy.org/en/latest/contributing/doc_guide.html#troubleshooting

python:
  install:
  - requirements: requirements.txt
