ignore:
- .git
- venv
- .venv
- env
- .env
- .tox
- node_modules
- vendor
- docs/plasmapy_sphinx
- plasmapy/formulary/braginskii.py

github:
  labels: []
  ignore_labels:
  - sourcery-ignore
  request_review: author
