codecov:
  notify:
    wait_for_ci: no
  require_ci_to_pass: no
coverage:
  range: 75..98
  status:
    project:
      default:
        threshold: 0.2%
        removed_code_behavior: adjust_base
        if_not_found: failure
    patch:
      default:
        threshold: 0.2%
        removed_code_behavior: adjust_base
        if_not_found: failure
