
deps-run: &deps-install
  name: Install Python dependencies
  command: |
    python3 -m venv venv
    . venv/bin/activate
    pip install -q --user -r requirements/automated-documentation-tests.txt
    pip install -q --user .

html-run: &doc-html
  name: Build HTML documentation
  command: make html SPHINXOPTS='-W'
  working_directory: docs

latex-run: &doc-latex
  name: Build LaTeX documentation
  command: |
    sudo apt update
    sudo apt install texlive texlive-xetex texlive-fonts-extra texlive-latex-extra texlive-plain-extra latexmk
    make latexpdf SPHINXOPTS='-W'
  working_directory: docs

version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: *deps-install
      - run: *doc-html
      - run: *doc-latex
