name: 🐛 Bug Report
description: Report a problem that you encountered when using PlasmaPy
labels: [Bug]
body:
- type: textarea
  id: what-happened
  attributes:
    label: Description of problem
    description: |
      Thank you for submitting a bug report — we really appreciate it! Please describe what you were doing and what went wrong.
  validations:
    required: true

- type: textarea
  id: expected-outcome
  attributes:
    label: Expected outcome
    description: |
      What did you expect to happen? (optional)
  validations:
    required: false

- type: textarea
  id: versions
  attributes:
    label: Versions
    description: |
      What version of PlasmaPy were you using when the problem occurred? This can be found using `plasmapy.__version__`. Optional.

- type: textarea
  id: sample-code
  attributes:
    label: Minimal complete verifiable example
    description: |
      Provide a minimal self-contained example to help us reproduce the problem. This will be automatically formatted into code, so no need for Markdown backticks. This is optional, but incredibly helpful!
    render: Python
  validations:
    required: false

- type: textarea
  id: log-output
  attributes:
    label: Relevant output
    description: |
      Copy and paste any relevant output here, such as a [traceback](https://docs.python.org/3/library/traceback.html) from the error. This will be automatically formatted into code, so no need for Markdown backticks. (optional)
    render: Python
  validations:
    required: false

- type: textarea
  id: extra
  attributes:
    label: Additional context
    description: |
      Please provide any contextual information that would help us fix the bug. (optional)
  validations:
    required: false
