name: 🐛 Bug Report
description: Help us by reporting a problem that you encountered when using PlasmaPy
labels: [Bug]
body:
- type: textarea
  id: description
  attributes:
    label: Description of problem
    description: |
      Thank you for submitting a bug report — we really appreciate it! Please describe what you were doing and what went wrong.
  validations:
    required: true

- type: textarea
  id: expected-outcome
  attributes:
    label: Expected outcome
    description: |
      What did you expect to happen? (optional)
  validations:
    required: false

- type: textarea
  id: minimal-example
  attributes:
    label: Minimal complete verifiable example
    description: |
      Provide a minimal self-contained example to help us reproduce the problem, along with any relevant output. This will be automatically formatted into code, so no need for Markdown backticks. (optional, but incredibly helpful!)
    render: Python
  validations:
    required: false

- type: textarea
  id: package-versions
  attributes:
    label: Package versions
    description: |
      What version of PlasmaPy were you using when the problem occurred? The version is given by `plasmapy.__version__`, or `pip show plasmapy` on the command line. (optional)

- type: textarea
  id: context
  attributes:
    label: Additional context
    description: |
      Please provide any contextual information that would help us fix the bug. (optional)
  validations:
    required: false
