name: 📝 Issue
description: Create a general issue that doesn't fit the other categories
body:
- type: textarea
  id: description
  attributes:
    label: Description of issue
    description: |
      Please describe the issue here.
  validations:
    required: true
