name: 📝 Issue
description: General issue
body:

- type: textarea
  id: description
  attributes:
    label: Description of issue
    description: |
      Please describe the issue here.
  validations:
    required: true


- type: textarea
  id: issue-description
  attributes:
    label: Description of issue
    description: |
      Thank you for raising an issue! Please enter the issue description here.
  validations:
    required: true
