name: 💡 Feature Request
description: |
  Request a new capability to help shape the future of PlasmaPy
labels: [Feature request]
body:
- type: textarea
  id: description
  attributes:
    label: Feature description
    description: |
      What new capability would you like added to PlasmaPy?
  validations:
    required: true

- type: textarea
  id: motivation
  attributes:
    label: Motivation
    description: |
      What would be the benefits from adding this feature? (optional)

- type: textarea
  id: solution
  attributes:
    label: Implementation strategy
    description: |
      How might we go about implementing this new capability? (optional)
  validations:
    required: false

- type: textarea
  id: additional-context
  attributes:
    label: Additional context
    description: |
      Please provide any additional helpful details here. (optional)
  validations:
    required: false
