name: 💡 Feature Request
description: Suggest a new capability to be added to PlasmaPy
labels: [Feature request]
body:
- type: textarea
  id: description
  attributes:
    label: Feature description
    description: |
      What new feature would you like added to PlasmaPy?
  validations:
    required: true

- type: textarea
  id: motivation
  attributes:
    label: Motivation
    description: |
      What would be the benefits from adding this feature? (optional)

- type: textarea
  id: solution
  attributes:
    label: Implementation strategy
    description: |
      How might we implement this new feature? (optional)
  validations:
    required: false

- type: textarea
  id: additional-context
  attributes:
    label: Additional context
    description: |
      Please provide any additional details here. (optional)
  validations:
    required: false
