name: plasmapy

channels:
  - astropy
  - conda-forge

dependencies:
  - python=3.7
  - numpy
  - scipy
  - astropy
  - h5py
  - matplotlib
  - mpmath
  - pandas
  - pillow
  - pip
  - xarray
  - pip:
    - numpydoc
    - pytest
    - lmfit
    - pygments>=2.4.1
    - sphinx>=3.2.0, <=3.5.2
    - sphinx-gallery
    - sphinx-automodapi
    - sphinx_rtd_theme != 0.5.2
