name: plasmapy

channels:
  - astropy
  - conda-forge

dependencies:
  - python=3.7
  - numpy
  - scipy
  - astropy
  - cython
  - h5py
  - matplotlib
  - mpmath
  - pillow
  - colorama
  - pip:
    - numpydoc
    - pytest
    - lmfit
    - sphinx
    - sphinx-gallery
    - sphinx-automodapi
    - sphinx_rtd_theme
