name: CI

on:
  push:
    branches:
    - main
    - stable
    - v*.*.*
    tags:
    - v*
  pull_request:
  workflow_dispatch:

env:
  DOC_TROUBLESHOOTING: "\nDocumentation troubleshooting guide:\n\nhttps://docs.plasmapy.org/en/latest/contributing/doc_guide.html#troubleshooting\n\n"

jobs:

  documentation:

    name: Documentation, Python 3.12, Ubuntu, nox
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install graphviz and pandoc
      run: sudo apt-get install graphviz pandoc

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: pip

    - name: Install nox uv
      run: python -m pip install --progress-bar off --upgrade nox uv

    - name: Cache
      uses: actions/cache@v4
      with:
        path: |
          .nox
        key: docs-${{ runner.os }}-${{ hashFiles('requirements.txt') }}

    - name: Build documentation with Sphinx
      run: nox -e docs -- -q

    - name: Intentional failure to test printing of doc troubleshooting
      run: nox -e docs -- -q

    - name: Print troubleshooting information on failure
      if: ${{ failure() }}
      run: echo $DOC_TROUBLESHOOTING
