name: Close PR

on:
  pull_request:
    types: [closed]

jobs:
  remove-labels:
    runs-on: ubuntu-latest
    steps:
    - name: Remove specific labels
      uses: actions/github-script@v6
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const { owner, repo, number } = context.issue;
          const pull = await github.rest.pulls.get({ owner, repo, pull_number: number });

          // If the pull request is not merged, do nothing
          if (!pull.data.merged) return;

          const labelsToRemove = [
            'help wanted',
            'Stale',
            'status: assigned',
            'status: in progress',
            'status: nearing completion',
            'status: on hold',
            'status: ready for review',
            'status: ready to merge'
          ];

          const { data: currentLabels } = await github.rest.issues.listLabelsOnIssue({ owner, repo, issue_number: number });
          for (let label of currentLabels) {
            if (labelsToRemove.includes(label.name)) {
              await github.rest.issues.removeLabel({ owner, repo, issue_number: number, name: label.name });
            }
          }
