name: Documentation

on:
  push:
    branches:
    - main
    - stable
    - v*.*.x
  pull_request:
  workflow_dispatch:

jobs:

  documentation:

    name: ${{ matrix.name }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        include:

        - name: Build documentation
          python: '3.10'
          noxenv: build_docs

    steps:

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install nox
      # Use a setup-nox action?
      run: python -m pip install --progress-bar off --upgrade nox

    - name: Install graphviz and pandoc
      # Use setup-graphviz and/or setup-pandoc actions?
      run: sudo apt install graphviz pandoc

    - name: Build documentation
      run: nox -e build_docs -- -q
