name: Style linters

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.0
  flake8:
    name: flake8
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v2
    - name: Install requirements
      run: pip install flake8
    - name: Run flake8
      run: flake8 . --count --show-source --statistics --extend-exclude ".jupyter"
  pydocstyle:
    name: pydocstyle
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v2
    - name: Install requirements
      run: pip install pydocstyle
    - name: Run pydocstyle
      run: pydocstyle . --count --source
