on:
  workflow_dispatch:
    inputs:
      target_pypi:
        description: Test PyPI or main PyPI?
        required: true
        default: https://test.pypi.org/legacy/
        type: choice
        options:
        - https://test.pypi.org/legacy/
        - https://pypi.org/legacy/
jobs:
  build:
    name: Packaging
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish_pure_python.yml@v1
    needs:
    - initial-tests
    - comprehensive-tests
    - documentation
    - codespell
    if: startsWith(github.ref, 'refs/tags/v')
    with:
      test_extras: tests
      test_command: pytest --pyargs plasmapy
      repository_url: ${{ github.event.inputs.tag }}
      upload_to_pypi: true
      runs-on: ubuntu-20.04
    secrets:
      pypi_token: ${{ secrets.TEST_PYPI_API_TOKEN }}
