name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Release tag
        required: true
        default: 0.9.0.relasetest
      DOI:
        description: Reserved DOI from Zenodo
        required: true
        default: 10.5281/zenodo.1238132


jobs:
  tag:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}

    - name: Install dependencies
      run: |
        pip install towncrier xonsh pre-commit

    - name: Update CITATION.cff, docs/about/citation.rst with the DOI for the new version.
      run: |
        echo "TODO"

    - name: Update and alphabetize the author list in docs/about/credits.rst
      run: |
        echo "TODO, just alphabetize"
    # Open a pull request to update .mailmap. - out of scope
    #

    # - name: Run pre-commit checks
    #   run: pre-commit run --all-files
    # - n

    - name: Setup git
      run: |
        git config --global user.email "team@plasmapy.org"
        git config --global user.name "PlasmaPy Automated Release Process"

    - name: Create changelog
      run: |
        towncrier build --yes --version ${{ github.event.inputs.tag }}
        # TODO Copy the relevant parts of the generated CHANGELOG.rst file into docs/whatsnew/0.9.0.rst.
        # TODO Add the entry for docs/whatsnew/0.9.0.rst in the table of contents in docs/whatsnew/index.rst.
        git commit -nm "Add changelog entries for v${{ github.event.inputs.tag }}"

    # - name: Update and run pre-commit  # TODO maybe out of scope
    #   run: |
    #     pre-commit autoupdate
    #     pre-commit run --all-files
    #     git commit -nm "Apply pre-commit fixes"

    - name: Tag the release
      run: |
        git tag "v${{ github.event.inputs.tag }}" -m "Version v{{ github.event.inputs.tag }}"
        git tag
    - name: Create branch and push to it # TODO push tag
      run: |
        git switch -c "${VERSION%?}x"  # replace last char with x
        git push -u origin "v${{ github.event.inputs.tag }}"
      env:
        VERSION: v${{ github.event.inputs.tag }}
  deploy:
    name: Deploy
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish_pure_python.yml@v1
    needs: [tag]
    with:
      test_extras: tests
      test_command: pytest --pyargs plasmapy
      repository_url: https://test.pypi.org/legacy/
    secrets:
      pypi_token: ${{ secrets.TEST_PYPI_API_TOKEN }}
