name: Size Labeler

on: [pull_request]

jobs:
  labeler:
    runs-on: ubuntu-latest
    name: Label PR size
    steps:
    - uses: codelytv/pr-size-labeler@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        xs_label: 'size: very small'
        xs_max_size: '10'
        s_label: 'size: small'
        s_max_size: '50'
        m_label: 'size: medium'
        m_max_size: '200'
        l_label: 'size: large'
        l_max_size: '400'
        xl_label: 'size: very large'
        fail_if_xl: 'false'
        message_if_xl: ''
        github_api_url: api.github.com
        files_to_ignore: ''
