name: CI

on:
  push:
    branches:
    - main
    - stable
    - v*.*.*
    tags:
    - v*
  pull_request:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:

  import-plasmapy:

    name: Import PlasmaPy, Python 3.10, Windows
    runs-on: windows-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: pip

    - name: Install tox and its extensions
      run: python -m pip install --progress-bar off --upgrade tox tox-uv

    - name: Import PlasmaPy
      run: tox -e py310-lowest_direct-pypi-import

  build-n-publish:
    name: Packaging, Python 3.12, Ubuntu
    runs-on: ubuntu-22.04

    steps:

    - uses: actions/checkout@v4

    - name: Get history and tags for SCM versioning to work
      run: |
        git fetch --prune --unshallow
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: pip

    - name: Install and upgrade requirements
      run: |
        pip install --progress-bar off setuptools numpy wheel setuptools_scm twine build pip --upgrade

    - name: Build a source distribution
      run: python -m build --sdist --outdir dist/

    - name: Build a binary wheel
      run: python -m build --wheel --outdir dist/

    - name: Twine check
      run: twine check dist/*

    - name: Install PlasmaPy with pip
      run: |
        pip install --progress-bar off .

    - name: Perform editable installation with tests & docs requirements sets
      run: |
        pip install --progress-bar off -e .[tests,docs]

  validate-citation-cff:
    runs-on: ubuntu-latest
    name: Validate CITATION.cff
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Validate CITATION.cff
      uses: dieghernan/cff-validator@v3
