name: CI

on:
  push:
    branches:
    - main
    - stable
    - v*.*.x
    tags:
    - v*
  pull_request:
  workflow_dispatch:

jobs:

  initial-tests:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

      matrix:
        include:

        - name: Python 3.8 (Windows)
          os: windows-latest
          python: 3.8
          noxenv: tests-3.8

        - name: Python 3.10
          os: ubuntu-latest
          noxenv: tests-3.10
          noxposargs: --durations=10
          python: '3.10'

        - name: Linters
          os: ubuntu-latest
          noxenv: linters

        - name: Codespell
          os: ubuntu-latest
          noxenv: codespell

        - name: Import package
          os: windows-latest
          noxenv: import_package

    steps:

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup nox
      uses: excitedleigh/setup-nox@v2.0.0

    - name: Run tests on ${{ matrix.name }}
      run: nox -s ${{ matrix.noxenv }} -- ${{ matrix.noxposargs }}

  comprehensive-tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    needs: initial-tests
    strategy:
      fail-fast: false

      matrix:
        include:

        - name: Python 3.9 (MacOS X)
          os: ubuntu-latest
          python: 3.9
          noxenv: tests-3.9

    steps:

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: ${{ matrix.name }}
      uses: excitedleigh/setup-nox@v2.0.0
      run: nox -s ${{ matrix.noxenv }} -- ${{ matrix.noxposargs }}

  documentation:

    name: Documentation
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install language-pack-fr and tzdata
      run: sudo apt-get install graphviz pandoc

    - name: Build documentation
      uses: excitedleigh/setup-nox@v2.0.0
      run: nox -e build_docs -- -q
