name: Update pinned requirements

on:
  schedule:
  - cron: 0 12 * * 1
  workflow_dispatch:

jobs:
  update-requirements:
    name: Regenerate requirements.txt
    runs-on: ubuntu-latest
    if: github.repository == 'PlasmaPy/PlasmaPy'

    steps:

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install uv
      run: python -m pip install uv

    - name: Generate top-level requirements.txt with all extras
      run: |
        python -m uv pip compile pyproject.toml -p 3.12 -U --all-extras -o requirements.txt

    - name: Generate doc build requirements file with most recent Python
      run: |
        python -m uv pip compile pyproject.toml -p 3.12 -U --extra docs -o requirements/requirements_py312_docs.txt

    - name: Generate requirements files for different Python versions
      run: |
        python -m uv pip compile pyproject.toml -p 3.12 -U --extra tests -o requirements/requirements_py312_tests.txt
        python -m uv pip compile pyproject.toml -p 3.11 -U --extra tests -o requirements/requirements_py311_tests.txt
        python -m uv pip compile pyproject.toml -p 3.10 -U --extra tests -o requirements/requirements_py310_tests.txt

    - name: Generate requirements file for minimum versions of dependencies
      run: |
        python -m uv pip compile pyproject.toml -p 3.10 -U --extra tests -o requirements/requirements_py310_tests_minimal.txt --resolution lowest-direct

    # When a PR is created by a GitHub Action, normally the checks will
    # not be run. While the simplest workaround would have been to open
    # and close the PR, an alternative is to authenticate with GitHub
    # App generated tokens (as done below). The instructions for how to
    # do this are in the documentation for the create-pull-request
    # action.

    - uses: tibdex/github-app-token@v2
      id: generate_token
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.APP_PRIVATE_KEY }}

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ steps.generate_token.outputs.token }}
        commit-message: Regenerate requirements.txt
        title: Update pinned requirements
        body: |
          This pull request (PR) regenerates the pinned requirements files used in continuous integration (CI) tests and by integrated development environments (IDEs), including [requirements.txt](https://github.com/PlasmaPy/PlasmaPy/blob/main/requirements.txt) and the files in the[requirements/](https://github.com/PlasmaPy/PlasmaPy/blob/main/requirements) directory.

          The purpose of periodically regenerating requirements files is to reduce the probability that tests will spontaneously start failing in other PRs due to a breaking change in a dependency. If all tests pass, please merge this PR. If any checks fail due to changes in the packages that we depend on, please use this PR to perform the fixes that are necessary to get the checks to pass again.

          In some cases, it may be necessary to put a *temporary* upper limit on the allowed versions of a dependency as defined in [pyproject.toml](https://github.com/PlasmaPy/PlasmaPy/blob/main/pyproject.toml). If this is necessary, please [create an issue](https://github.com/PlasmaPy/PlasmaPy/issues/new?title=Remove+upper+limit+on+version+of) that this upper limit should be removed.
        labels: No changelog entry needed, dependencies
        delete-branch: true
        base: main
