name: Update pinned requirements

on:
  schedule:
  - cron: 0 6 * * 1
  workflow_dispatch:

jobs:
  update-requirements:
    runs-on: ubuntu-latest
    if: github.repository == 'PlasmaPy/PlasmaPy'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install pip-tools
      run: python -m pip install pip-tools

    - name: Generate requirements.txt
      run: pip-compile --all-extras --output-file=requirements.txt --resolver=backtracking -r -U

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_SCOPED_TOKEN }}
      with:
        commit-message: Regenerate requirements.txt
        title: Update pinned requirements
        body: >
          This PR
          [regenerates](https://www.youtube.com/watch?v=qWM7l9SAipg&themeRefresh=1)
          the pinned requirements contained in
          [\`requirements.txt\`](https://github.com/PlasmaPy/PlasmaPy/blob/main/requirements.txt).
          This file defines the Python environment used by certain
          GitHub Actions checks, as well as by IDEs like PyCharm and VS
          Code.

          If all tests pass, please merge this PR. If any checks fail
          due to changes in the packages that we depend on, this PR may
          be used to perform the fixes that are necessary to get the
          checks to pass again.

          The pinned requirements are created by the command

          \`\`\`console
          pip-compile --all-extras --output-file=requirements.txt --resolver=backtracking -r -U
          \`\`\`

          which uses \`pip-compile\` from
          [\`pip-tools\`](https://pip-tools.readthedocs.io/).
        labels: No changelog entry needed, dependencies
        delete-branch: true
        base: main
